### ISSUE TITLE
webview doesn't show up

### ISSUE THREAD

**Issue by hicham4i** [5exyGuy/altv-vcode#1]
after starting the resource and pressing f4 you can see the cursor focus but the webview doesn't show up

**Comment by 5exyGuy** [comment]
> after starting the resource and pressing f4 you can see the cursor focus but the webview doesn't show up

Have you tried pressing F4 again? I'll check it when I will get home.

**Comment by hicham4i** [comment]
yes i tried. I even opened it in cef remote debugger the width and height of the container are 0 so I guess maybe the data didn't get attached or something
