### ISSUE TITLE
how to import 

### ISSUE THREAD

**Issue by FDiskas** [5exyGuy/altv-vcode#2]
Hi, thanks for this tool. 
I'm trying to use natives within client?
```
ReferenceError: native is not defined
```

**Comment by 5exyGuy** [comment]
You must be doing something wrong. Each "file" has it's own environment set with the autocomplete. If there's no autocompletion for client natives then you must be in server environment or there's an error. Also make sure that `client/index.js` has `import native from 'natives';`. Anyways, I'll try to fix some issues and add a few small features when I have time.
