### ISSUE TITLE
[BUG] "Execute" disappears when pressing DEL

### ISSUE THREAD

**Issue by DatMayo** [5exyGuy/altv-vcode#3]
When you press DEL while writing some temporary code, the button "=> EXECUTE F7" disappears. Even the file on the left side is removed

Example: https://i.imgur.com/k9Tntk6.png

**Comment by 5exyGuy** [comment]
For now, It should be like that, because DELETE key deletes the current file. For a temporary solution, you can remove if statement from keyup event listener in `client/index.js`. Right now I am working on some features and will try to fix observed errors.
